# Generated by Django 2.1.15 on 2020-10-06 18:49

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created',
            field=models.DateTimeField(default=django.utils.datetime_safe.date),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='modified',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.date),
            preserve_default=False,
        ),
    ]
