# Generated by Django 2.1.15 on 2020-10-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20201006_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created',
        ),
        migrations.RemoveField(
            model_name='client',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='client',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='client',
            name='slug',
        ),
    ]
