# Generated by Django 2.1.15 on 2020-09-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
