# Generated by Django 2.1.15 on 2020-09-25 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200924_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Client_Name',
            new_name='name',
        ),
    ]
