# Generated by Django 2.1.15 on 2020-10-06 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200924_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
